//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.ConsoleClientForDayOfTheWeek.DayOfTheWeekService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfTheWeekService.IDayOfWeekService")]
    public interface IDayOfWeekService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IDayOfWeekService/GetDayOfWeekInBulgarianResponse")]
        string GetDayOfWeekInBulgarian(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IDayOfWeekService/GetDayOfWeekInBulgarianResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime dateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfWeekServiceChannel : _02.ConsoleClientForDayOfTheWeek.DayOfTheWeekService.IDayOfWeekService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfWeekServiceClient : System.ServiceModel.ClientBase<_02.ConsoleClientForDayOfTheWeek.DayOfTheWeekService.IDayOfWeekService>, _02.ConsoleClientForDayOfTheWeek.DayOfTheWeekService.IDayOfWeekService {
        
        public DayOfWeekServiceClient() {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeekInBulgarian(System.DateTime dateTime) {
            return base.Channel.GetDayOfWeekInBulgarian(dateTime);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime dateTime) {
            return base.Channel.GetDayOfWeekInBulgarianAsync(dateTime);
        }
    }
}
