//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.UseInclude
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int WorkHoursLogID { get; set; }
        public string ActionType { get; set; }
        public Nullable<int> WorkHoursID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DateOld { get; set; }
        public System.DateTime DateNew { get; set; }
        public string Tasks { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Comments { get; set; }
    }
}
