//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGetNumberOfRepetitions")]
public interface IGetNumberOfRepetitions
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetNumberOfRepetitions/GetNumberOfRepetitions", ReplyAction="http://tempuri.org/IGetNumberOfRepetitions/GetNumberOfRepetitionsResponse")]
    int GetNumberOfRepetitions(string hay, string needle);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetNumberOfRepetitions/GetNumberOfRepetitions", ReplyAction="http://tempuri.org/IGetNumberOfRepetitions/GetNumberOfRepetitionsResponse")]
    System.Threading.Tasks.Task<int> GetNumberOfRepetitionsAsync(string hay, string needle);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGetNumberOfRepetitionsChannel : IGetNumberOfRepetitions, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetNumberOfRepetitionsClient : System.ServiceModel.ClientBase<IGetNumberOfRepetitions>, IGetNumberOfRepetitions
{
    
    public GetNumberOfRepetitionsClient()
    {
    }
    
    public GetNumberOfRepetitionsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetNumberOfRepetitionsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetNumberOfRepetitionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetNumberOfRepetitionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetNumberOfRepetitions(string hay, string needle)
    {
        return base.Channel.GetNumberOfRepetitions(hay, needle);
    }
    
    public System.Threading.Tasks.Task<int> GetNumberOfRepetitionsAsync(string hay, string needle)
    {
        return base.Channel.GetNumberOfRepetitionsAsync(hay, needle);
    }
}
