using System;

class ProvideShortInfoAboutOtherLanguages
{
    static void Main()
    {
        Console.WriteLine("\r\nC++:\r\nC# is a distinct language from C++. C++ is designed for general object oriented programming in the days when the typical computer was a standalone machine running a command line-based user interface. C++ is a general-purpose programming language with high-level and low-level capabilities. It is a statically typed, free-form, multi-paradigm, usually compiled language supporting procedural programming, data abstraction, object-oriented programming, and generic programming.\r\nC++ is regarded as a mid-level language. This indicates that C++ comprises a combination of both high-level and low-level language features. C# is designed specifically to work with the .Net and is geared to the modern environment of Windows and mouse-controlled user interface, networks and the internet.");
        Console.WriteLine("\r\nPHP:\r\nPHP is a server-side scripting language designed for web development but also used as a general-purpose programming language. PHP is now installed on more than 244 million websites and 2.1 million web servers. Originally created by Rasmus Lerdorf in 1995, the reference implementation of PHP is now produced by The PHP Group.[3] While PHP originally stood for Personal Home Page, it now stands for PHP: Hypertext Preprocessor, a recursive acronym.\r\nPHP code is interpreted by a web server with a PHP processor module which generates the resulting web page: PHP commands can be embedded directly into an HTML source document rather than calling an external file to process data. It has also evolved to include a command-line interface capability and can be used in standalone graphical applications.\r\nPHP is free software released under the PHP License, which is incompatible with the GNU General Public License (GPL) due to restrictions on the usage of the term PHP. PHP can be deployed on most web servers and also as a standalone shell on almost every operating system and platform, free of charge.");
        Console.WriteLine("\r\nHTML:\r\nHyperText Markup Language (HTML) is the main markup language for creating web pages and other information that can be displayed in a web browser.\r\nThe purpose of a web browser is to read HTML documents and compose them into visible or audible web pages. The browser does not display the HTML tags, but uses the tags to interpret the content of the page.");
        Console.WriteLine("\r\nDifferences with C#:\r\nUnlike C++, C# is considered a high level programming language. It uses a more advanced level of abstraction with allows easier learning and faster softwear development. C# is an object orientated language while C++ supports many different programming styles.\r\n\r\nUnlike C#, PHP is an open source project and is developed by its community. PHP can be embedded dirrectly into the HTML code and can be executed without compilation. While PHP supports OOP, this feature is less advanced that C#'s equivalent.\r\n\r\nUnlike C#, HTML is a markup language. It provides the browsers with the information, nessesarry to display correctly a certain content. HTML is not meant for calculations and can't be used for serverside scripting.");
    }
}

